package com.optms.app.service;

import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
public class SchemaMaintenanceService implements CommandLineRunner {

    private final JdbcTemplate jdbcTemplate;

    @Override
    public void run(String... args) {
        jdbcTemplate.execute("ALTER TABLE IF EXISTS tabela_frete DROP COLUMN IF EXISTS usuario_id");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS companies (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "name TEXT, " +
                "social_name TEXT, " +
                "document TEXT, " +
                "createdAt TIMESTAMP, " +
                "active BOOLEAN DEFAULT TRUE, " +
                "apikey VARCHAR(22))");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS companies ADD COLUMN IF NOT EXISTS social_name TEXT");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS companies ADD COLUMN IF NOT EXISTS document TEXT");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS companies ADD COLUMN IF NOT EXISTS createdAt TIMESTAMP");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS companies ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS companies ADD COLUMN IF NOT EXISTS apikey VARCHAR(22)");
        jdbcTemplate.execute("UPDATE companies SET active = TRUE WHERE active IS NULL");
        jdbcTemplate.execute("CREATE UNIQUE INDEX IF NOT EXISTS uq_companies_apikey ON companies (apikey)");
    }
}
