package com.optms.app.service;

import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
public class SchemaMaintenanceService implements CommandLineRunner {

    private final JdbcTemplate jdbcTemplate;

    @Override
    public void run(String... args) {
        jdbcTemplate.execute("ALTER TABLE IF EXISTS tabela_frete DROP COLUMN IF EXISTS usuario_id");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS tabela_frete ALTER COLUMN uf_origem TYPE VARCHAR(20)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS tabela_frete ALTER COLUMN uf_origem DROP NOT NULL");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS tabela_frete ADD COLUMN IF NOT EXISTS tipo VARCHAR(100)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS tabela_frete ADD COLUMN IF NOT EXISTS vigencia_inicio DATE");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS tabela_frete ADD COLUMN IF NOT EXISTS vigencia_fim DATE");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS objeto_frete ADD COLUMN IF NOT EXISTS uf_origem VARCHAR(20)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS objeto_frete ADD COLUMN IF NOT EXISTS uf_destino VARCHAR(20)");
        try {
            jdbcTemplate.execute("UPDATE objeto_frete SET uf_destino = uf WHERE uf_destino IS NULL AND uf IS NOT NULL");
        } catch (RuntimeException exception) {
            // H2 tests may start without this table because Hibernate DDL is disabled there.
        }
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS companies (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "name TEXT, " +
                "social_name TEXT, " +
                "document TEXT, " +
                "created_at TIMESTAMP, " +
                "active BOOLEAN DEFAULT TRUE, " +
                "apikey VARCHAR(22))");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS companies ADD COLUMN IF NOT EXISTS social_name TEXT");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS companies ADD COLUMN IF NOT EXISTS document TEXT");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS companies ADD COLUMN IF NOT EXISTS created_at TIMESTAMP");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS companies ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS companies ADD COLUMN IF NOT EXISTS apikey VARCHAR(22)");
        jdbcTemplate.execute("UPDATE companies SET active = TRUE WHERE active IS NULL");
        jdbcTemplate.execute("CREATE UNIQUE INDEX IF NOT EXISTS uq_companies_apikey ON companies (apikey)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS lotes_treino ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'TREINANDO'");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS lotes_treino ADD COLUMN IF NOT EXISTS mensagem_erro TEXT");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS lotes_treino ADD COLUMN IF NOT EXISTS finalizado_em TIMESTAMP");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS lotes_treino ADD COLUMN IF NOT EXISTS artifacts_id VARCHAR(255)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS lotes_treino ADD COLUMN IF NOT EXISTS n_registros_treino INTEGER DEFAULT 0");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS lotes_treino ADD COLUMN IF NOT EXISTS linhas_descartadas INTEGER DEFAULT 0");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS lotes_treino ADD COLUMN IF NOT EXISTS mae_kfold DECIMAL(8, 4)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS lotes_treino ADD COLUMN IF NOT EXISTS rmse_kfold DECIMAL(8, 4)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS lotes_treino ADD COLUMN IF NOT EXISTS r2_kfold DECIMAL(6, 4)");
        jdbcTemplate.execute("ALTER TABLE IF EXISTS lotes_treino ADD COLUMN IF NOT EXISTS origem_input_ids TEXT");
        try {
            jdbcTemplate.execute("DO $$ BEGIN " +
                    "IF to_regclass('public.catalogo_artefatos_ml') IS NOT NULL THEN " +
                    "CREATE UNIQUE INDEX IF NOT EXISTS uq_catalogo_artefatos_company_ativo ON catalogo_artefatos_ml (company_id) WHERE ativo = TRUE; " +
                    "END IF; " +
                    "END $$");
        } catch (RuntimeException exception) {
            // H2 used by tests does not support PostgreSQL DO blocks.
        }
    }
}
