CREATE TABLE IF NOT EXISTS public.tabela_frete (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    uf_origem CHAR(2) NOT NULL,
    nome VARCHAR(255),
    ativa BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS public.objeto_frete (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabela_id BIGINT,
    tipo_objeto VARCHAR(20),  -- PARTIDA | COMPONENTE
    uf CHAR(2),               -- destino para COMPONENTEs; NULL = aplica a todos
    base_calculo VARCHAR(50),
    tipo_calculo VARCHAR(50),
    config_faixas JSONB,
    nome VARCHAR(100),
    sobre_frete_partida BOOLEAN DEFAULT FALSE
);

create table IF NOT EXISTS public.users(
	id BIGINT GENERATED BY DEFAULT AS identity primary key,
	name text,
	companyId BIGINT,
    email text,
    password text,
	createdAt timestamp,
	active boolean default TRUE
);

create table IF NOT EXISTS public.companies(
	id BIGINT GENERATED BY DEFAULT AS identity primary key,
	name text,
	social_name text,
	document text,
	createdAt timestamp,
	active boolean default TRUE,
	apikey VARCHAR(22) NOT NULL
);

create table IF NOT EXISTS public.external_apikeys(
	id BIGINT GENERATED BY DEFAULT AS identity primary key,
	custom_name text,
	apikey VARCHAR(22) NOT NULL,
	companyId BIGINT,
	active boolean
);

-- Índice GIN para buscas em campos JSONB
CREATE INDEX IF NOT EXISTS idx_objeto_frete_faixas ON objeto_frete USING GIN (config_faixas);

CREATE UNIQUE INDEX IF NOT EXISTS uq_companies_apikey
    ON companies (apikey);

CREATE UNIQUE INDEX IF NOT EXISTS uq_external_apikeys_apikey
    ON external_apikeys (apikey);

DROP INDEX IF EXISTS uq_tabela_frete_uf_origem_ativa;
DROP INDEX IF EXISTS uq_tabela_frete_company_uf_origem_ativa;

--
-- Tabelas relacionadas ao escopo de ML
--

-- 1. TABELA PAI: LOTES DE TREINO (Gera o input_id)
CREATE TABLE IF NOT EXISTS public.lotes_treino (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    descricao TEXT,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_lotes_company FOREIGN KEY (company_id) 
        REFERENCES public.companies(id) ON DELETE CASCADE
);

-- Índice para acelerar a busca de lotes de uma empresa específica
CREATE INDEX IF NOT EXISTS idx_lotes_company_id ON public.lotes_treino(company_id);


-- 2. TABELA FILHA: DADOS OPERACIONAIS DE TREINO (Onde o seu SELECT vai atuar)
CREATE TABLE IF NOT EXISTS public.dados_treino_operacional (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    input_id BIGINT NOT NULL, -- O agrupador do lote solicitado
    
    -- Variáveis Contínuas (Físicas e Fiscais)
    peso_total_bruto DECIMAL(12, 2) NOT NULL,
    metro_cubico DECIMAL(10, 4) NOT NULL,
    valor_nf DECIMAL(15, 2) NOT NULL,
    volume_nf INTEGER NOT NULL,
    
    -- Variáveis Categóricas (Regras da Operação)
    tipo_de_frete_nf VARCHAR(10) NOT NULL,
    via_de_transporte VARCHAR(50) NOT NULL,
    uf_emitente_nf CHAR(2) NOT NULL,
    uf_destinatario_nf CHAR(2) NOT NULL,
    
    -- Variável Alvo (Target)
    transit_time_dias INTEGER NOT NULL,
    
    CONSTRAINT fk_dados_lote FOREIGN KEY (input_id) 
        REFERENCES public.lotes_treino(id) ON DELETE CASCADE
);

-- ÍNDICE CRUCIAL: Acelera o comando "SELECT * FROM dados_treino_operacional WHERE input_id = :id"
CREATE INDEX IF NOT EXISTS idx_dados_treino_input_id ON public.dados_treino_operacional(input_id);


-- 3. TABELA: CATÁLOGO DE ARTEFATOS (Model Registry & Linhagem)
CREATE TABLE IF NOT EXISTS public.catalogo_artefatos_ml (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifacts_id VARCHAR(255) NOT NULL UNIQUE, -- Nome físico/UUID do arquivo .pkl (ex: modelo_c1_lote3.pkl)
    company_id BIGINT NOT NULL,
    input_id BIGINT NOT NULL, -- Rastreabilidade: aponta para o lote exato que treinou este modelo
    
    -- Métricas de Performance avaliadas no K-Fold
    mae_kfold DECIMAL(8, 4) NOT NULL,
    rmse_kfold DECIMAL(8, 4) NOT NULL,
    r2_kfold DECIMAL(6, 4) NOT NULL,
    usou_feature_engineering BOOLEAN DEFAULT TRUE,
    
    -- Controle de Estado do Ciclo de Vida do Modelo
    ativo BOOLEAN DEFAULT FALSE,
    treinado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_artefatos_company FOREIGN KEY (company_id) 
        REFERENCES public.companies(id) ON DELETE CASCADE,
        
    CONSTRAINT fk_artefatos_lote FOREIGN KEY (input_id) 
        REFERENCES public.lotes_treino(id) ON DELETE RESTRICT -- Evita apagar o lote se o modelo ainda existir
);

-- Índices para busca rápida do modelo ativo da empresa no endpoint /predict/
CREATE INDEX IF NOT EXISTS idx_artefatos_company_ativo ON public.catalogo_artefatos_ml(company_id, ativo);
CREATE INDEX IF NOT EXISTS idx_artefatos_input_id ON public.catalogo_artefatos_ml(input_id);