\set ON_ERROR_STOP on

SELECT 'CREATE DATABASE "TMA"'
WHERE NOT EXISTS (
    SELECT 1
    FROM pg_database
    WHERE datname = 'TMA'
)
\gexec

\connect TMA

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

CREATE TABLE public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    social_name TEXT,
    document TEXT,
    created_at TIMESTAMP,
    active BOOLEAN DEFAULT TRUE,
    apikey VARCHAR(22) NOT NULL
);

CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    company_id BIGINT,
    email TEXT,
    password TEXT,
    created_at TIMESTAMP,
    active BOOLEAN DEFAULT TRUE
);

CREATE TABLE public.tabela_frete (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    uf_origem CHAR(2) NOT NULL,
    nome VARCHAR(255),
    ativa BOOLEAN DEFAULT TRUE
);

CREATE TABLE public.objeto_frete (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabela_id BIGINT,
    tipo_objeto VARCHAR(20),
    uf CHAR(2),
    base_calculo VARCHAR(50),
    tipo_calculo VARCHAR(50),
    config_faixas JSONB,
    nome VARCHAR(100),
    sobre_frete_partida BOOLEAN DEFAULT FALSE
);

CREATE TABLE public.external_apikeys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    custom_name TEXT,
    apikey VARCHAR(22) NOT NULL,
    company_id BIGINT,
    active BOOLEAN
);

CREATE INDEX idx_objeto_frete_faixas
    ON public.objeto_frete USING GIN (config_faixas);

CREATE UNIQUE INDEX uq_companies_apikey
    ON public.companies (apikey);

CREATE UNIQUE INDEX uq_external_apikeys_apikey
    ON public.external_apikeys (apikey);

INSERT INTO public.companies (name, social_name, document, created_at, active, apikey)
VALUES
    ('Company 1', 'Company 1 LTDA', '11111111000101', CURRENT_TIMESTAMP, TRUE, 'APIKEY001'),
    ('Company 2', 'Company 2 LTDA', '22222222000102', CURRENT_TIMESTAMP, TRUE, 'APIKEY002');

INSERT INTO public.users (name, company_id, email, password, created_at, active)
SELECT seed.name, company.id, seed.email, seed.password, CURRENT_TIMESTAMP, TRUE
FROM public.companies AS company
JOIN (
    VALUES
        ('APIKEY001', 'Usuario 1 Company 1', 'usuario1.company1@tma.local', '$2y$10$b25gluQZkO3Fa46tEOiaS.MNhEpoDabDNlJCcbhqF/vikqXzWHR9e'),
        ('APIKEY001', 'Usuario 2 Company 1', 'usuario2.company1@tma.local', '$2y$10$b25gluQZkO3Fa46tEOiaS.MNhEpoDabDNlJCcbhqF/vikqXzWHR9e'),
        ('APIKEY002', 'Usuario 1 Company 2', 'usuario1.company2@tma.local', '$2y$10$b25gluQZkO3Fa46tEOiaS.MNhEpoDabDNlJCcbhqF/vikqXzWHR9e'),
        ('APIKEY002', 'Usuario 2 Company 2', 'usuario2.company2@tma.local', '$2y$10$b25gluQZkO3Fa46tEOiaS.MNhEpoDabDNlJCcbhqF/vikqXzWHR9e')
) AS seed(apikey, name, email, password)
    ON company.apikey = seed.apikey;
